# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Signal' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Signal
  pod 'SnapKit', '~> 0.22.0'
  pod 'Alamofire', '~> 3.5.0'

  target 'SignalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SignalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
